#pragma once
#include "Tuple.h"
#include "Shape.h"
#include "Ray.h"
#include "Intersection.h"
#include "Canvas.h"
#include "Mat.h"
#include "PPM.h"
#include "World.h"
#include "Camera.h"
#include "Patterns.h"
#include "yaml.h"
#include <time.h>
